/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    BasketVault: {
      address: "0xe72fbf68536d29d3a9e0d897c2ae813b7b279058",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "config",
              type: "tuple",
              internalType: "struct BasketVault.Config",
              components: [
                {
                  name: "router",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "factory",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "whbarHelper",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "whbar",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "hbarUsdFeed",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "maxOracleAge",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "driftBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "slippageBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxTradeBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "scheduledGas",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "guardLeg",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxDeviationBps",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "legConfigs",
              type: "tuple[]",
              internalType: "struct BasketVault.LegConfig[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "pool",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "weightBps",
                  type: "uint16",
                  internalType: "uint16",
                },
              ],
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "DEAD_SHARES",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_INTERVAL",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_INTERVAL",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_SCHEDULED_GAS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [
            {
              name: "minShares",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "shares",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "driftBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "factory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISaucerSwapV2Factory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "guardLeg",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hbarUsd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hbarUsdFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "holdings",
          inputs: [],
          outputs: [
            {
              name: "rows",
              type: "tuple[]",
              internalType: "struct BasketVault.Holding[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "balance",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "valueWhbar",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "targetBps",
                  type: "uint16",
                  internalType: "uint16",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "initialize",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "legs",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct BasketVault.Leg[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "pool",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "fee",
                  type: "uint24",
                  internalType: "uint24",
                },
                {
                  name: "tokenIsToken0",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "weightBps",
                  type: "uint16",
                  internalType: "uint16",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxDeviationBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxOracleAge",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxTradeBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nav",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "navUsd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextRunAt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingSchedule",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rearm",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rebalance",
          inputs: [],
          outputs: [
            {
              name: "traded",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rebalanceInterval",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "redeem",
          inputs: [
            {
              name: "shares",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "whbarOut",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "legAmounts",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "redeemExcept",
          inputs: [
            {
              name: "shares",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "skipLegsMask",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "whbarOut",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "legAmounts",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "router",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISaucerSwapV2Router",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "runScheduled",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "scheduledGas",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sharePriceUsd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "shareToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "slippageBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "startAutomation",
          inputs: [
            {
              name: "interval",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stopAutomation",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "whbar",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whbarHelper",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IWhbarHelper",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whbarWeightBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdrawFuel",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address payable",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "AutomationStarted",
          inputs: [
            {
              name: "interval",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AutomationStopped",
          inputs: [],
          anonymous: false,
        },
        {
          type: "event",
          name: "BookingFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deposited",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "hbarIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "valueAdded",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "shares",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Initialized",
          inputs: [
            {
              name: "shareToken",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "LegsSkipped",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "skipLegsMask",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Rebalanced",
          inputs: [
            {
              name: "navBefore",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "navAfter",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "traded",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Redeemed",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "shares",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "whbarOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "legAmounts",
              type: "uint256[]",
              indexed: false,
              internalType: "uint256[]",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RunBooked",
          inputs: [
            {
              name: "schedule",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "expiry",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ScheduleDeleted",
          inputs: [
            {
              name: "schedule",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "responseCode",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ScheduledRun",
          inputs: [
            {
              name: "traded",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ScheduledRunFailed",
          inputs: [
            {
              name: "reason",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Swapped",
          inputs: [
            {
              name: "tokenIn",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenOut",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amountIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "amountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "AutomationActive",
          inputs: [],
        },
        {
          type: "error",
          name: "BadConfig",
          inputs: [],
        },
        {
          type: "error",
          name: "BadInterval",
          inputs: [
            {
              name: "interval",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "BadOraclePrice",
          inputs: [
            {
              name: "answer",
              type: "int256",
              internalType: "int256",
            },
          ],
        },
        {
          type: "error",
          name: "BadSkipMask",
          inputs: [
            {
              name: "skipLegsMask",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "HtsCallFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "InsufficientShares",
          inputs: [
            {
              name: "shares",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minShares",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NotAutomated",
          inputs: [],
        },
        {
          type: "error",
          name: "NotInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlyOwnerOrSelf",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlySelf",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "PoolPriceDeviates",
          inputs: [
            {
              name: "poolHbarUsd",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "oracleHbarUsd",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "RunAlreadyPending",
          inputs: [
            {
              name: "schedule",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SafeCastOverflowedIntDowncast",
          inputs: [
            {
              name: "bits",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "value",
              type: "int256",
              internalType: "int256",
            },
          ],
        },
        {
          type: "error",
          name: "SafeCastOverflowedUintToInt",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ScheduleFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "StaleOracle",
          inputs: [
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ZeroAmount",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41298976,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
